[build]
  publish = "web"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.usdz"
  [headers.values]
    Content-Type = "model/vnd.usdz+zip"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=0, must-revalidate"
